server:
  port: 8082

spring:
  application:
    name: "srv-back-rest-grpc"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

integration:
  grpc:
    targetService: "srv-back-grpc-kafka:9091"

grpc:
  server:
    port: 9090