version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # Исправлено
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  srv-client-graphql-rest:
    build: ./srv-client-graphql-rest
    container_name: srv-client-graphql-rest
    ports:
      - "8081:8081"

  srv-back-rest-grpc:
    build: ./srv-back-rest-grpc
    container_name: srv-back-rest-grpc
    ports:
      - "8082:8082"

  srv-back-grpc-kafka:
    build: ./srv-back-grpc-kafka
    container_name: srv-back-grpc-kafka
    ports:
      - "8083:8083"

  srv-back-kafka:
    build: ./srv-back-kafka
    container_name: srv-back-kafka
    ports:
      - "8084:8084"