apiVersion: v1
kind: Service
metadata:
  name: srv-client-graphql-rest-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: srv-client-graphql-rest