http-item-service:
  httpMethod: POST
  httpUrl: http://srv-back-rest-grpc:8082/api/getItemById
  mediaType: "application/json"
  httpSettings:
    httpCallTimeoutSeconds: 10000
    connectTimeout: 10000s

server:
  port: 8081

spring:
  application:
    name: srv-client-graphql-rest
  graphql:
    graphiql:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
