apiVersion: v1
kind: ConfigMap
metadata:
  name: srv-back-rest-grpc-config
data:
  application.yml: |
    server:
      port: 8082

    spring:
      application:
        name: "srv-back-rest-grpc"
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher

    integration:
      grpc:
        targetService: "172.22.222.182:9091"

    grpc:
      server:
        port: 9090
  
