apiVersion: v1
kind: Service
metadata:
  name: srv-back-rest-grpc-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30002
  selector:
    app: srv-back-rest-grpc