apiVersion: v1
kind: Service
metadata:
  name: srv-back-grpc-kafka-service
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30003
  selector:
    app: srv-back-grpc-kafka